const app = getApp()
Page({
  data: { allowed: false, role: '', phoneTail: '', qrToken: '', proofImages: [], candidates: [], stationOptions: [], stationIndex: 0, batchStationId: '', verifyMode: '有人核销', duplicateTailWarnings: [], prepSummary: [], orders: [], doneCount: 0, totalCount: 0, percent: 0 },
  onShow() { this.guard().then((ok) => ok && this.loadStations()) },
  async guard() { const res = await app.call('checkAdmin'); if (!res.ok || !res.isAdmin) { wx.navigateBack(); return false } this.setData({ allowed: true, role: res.role }); return true },
  async loadStations() { const res = await app.call('getVerifierWorkspace'); if (!res.ok) return; const options = (res.batchStations || []).filter((row) => ['已确认配送', '自提进行中'].includes(row.status)).map((row) => ({ id: row._id, label: `${row.stationName || row.stationId} · ${row.verifyMode}`, verifyMode: row.verifyMode || '有人核销', duplicateTailWarnings: row.duplicateTailWarnings || [] })); if (!options.length) { this.setData({ stationOptions: [], batchStationId: '', orders: [] }); return } this.setData({ stationOptions: options, stationIndex: 0, batchStationId: options[0].id, verifyMode: options[0].verifyMode, duplicateTailWarnings: options[0].duplicateTailWarnings }, () => this.loadPrep()) },
  onStationChange(e) { const index = Number(e.detail.value), row = this.data.stationOptions[index]; this.setData({ stationIndex: index, batchStationId: row.id, verifyMode: row.verifyMode, duplicateTailWarnings: row.duplicateTailWarnings, candidates: [], proofImages: [] }, () => this.loadPrep()) },
  async loadPrep() { const res = await app.call('prepList', { batchStationId: this.data.batchStationId }); if (!res.ok) return; const orders = res.orders || []; const done = orders.filter((row) => ['已完成', '已放置待自取', '已完成未取'].includes(row.status)).length; this.setData({ prepSummary: res.summary || [], orders, doneCount: done, totalCount: orders.length, percent: orders.length ? Math.round(done / orders.length * 100) : 0 }) },
  goBack() { wx.navigateBack() }, onTail(e) { this.setData({ phoneTail: e.detail.value }) },
  async chooseProof() { const picked = await new Promise((resolve) => wx.chooseMedia({ count: 3, mediaType: ['image'], sourceType: ['camera', 'album'], success: resolve, fail: () => resolve(null) })); if (!picked) return; wx.showLoading({ title: '上传交付照片' }); try { const images = []; for (const [index, file] of picked.tempFiles.entries()) { const up = await wx.cloud.uploadFile({ cloudPath: `fulfillment/${this.data.batchStationId}-${Date.now()}-${index}.jpg`, filePath: file.tempFilePath }); images.push(up.fileID) } this.setData({ proofImages: images }) } finally { wx.hideLoading() } },
  scanCode() { wx.scanCode({ success: (res) => { let qrToken = String(res.result || '').trim(); try { const parsed = JSON.parse(qrToken); qrToken = parsed.pickupQrToken || parsed.qrToken || qrToken } catch (err) {} this.setData({ qrToken }, () => this.verify({ method: 'scan', qrToken })) } }) },
  verifyTail() { this.verify({ method: 'tail', phoneTail: this.data.phoneTail }) },
  verifyCandidate(e) { this.verify({ method: 'manual', orderId: e.currentTarget.dataset.id }) },
  async verify(payload) { if (this._verifying || !this.data.proofImages.length) { if (!this.data.proofImages.length) wx.showToast({ title: '请先上传交付照片', icon: 'none' }); return } this._verifying = true; let res = await app.call('verifyOrder', { batchStationId: this.data.batchStationId, images: this.data.proofImages, ...payload }); if (!res.ok && this.data.role === 'superAdmin' && /跨站/.test(res.msg || '')) { const modal = await new Promise((resolve) => wx.showModal({ title: '异常跨站核销', editable: true, placeholderText: '二次确认并填写原因', success: resolve })); if (modal.confirm && modal.content.trim()) res = await app.call('verifyOrder', { batchStationId: this.data.batchStationId, images: this.data.proofImages, crossStationConfirmed: true, reason: modal.content.trim(), ...payload }) } this._verifying = false; if (res.ok && res.ambiguous) { this.setData({ candidates: res.candidates || [] }); return } wx.showToast({ title: res.ok ? '核销成功' : (res.msg || '核销失败'), icon: 'none' }); if (res.ok) this.setData({ phoneTail: '', qrToken: '', candidates: [], proofImages: [] }); this.loadPrep() },
  async markArrived() { const res = await app.call('markArrived', { batchStationId: this.data.batchStationId }); wx.showToast({ title: res.ok ? '已开始自提' : (res.msg || '失败'), icon: 'none' }); this.loadStations() },
  async contact(e) { const modal = await new Promise((resolve) => wx.showModal({ title: '记录迟到联系', editable: true, placeholderText: '如：已接通，约定取货', success: resolve })); if (!modal.confirm) return; const res = await app.call('contactOrder', { orderId: e.currentTarget.dataset.id, contactStatus: '已联系', note: modal.content || '' }); wx.showToast({ title: res.ok ? '已记录' : (res.msg || '失败'), icon: 'none' }) },
  async placeAll() { if (!this.data.proofImages.length) { wx.showToast({ title: '请先上传现场照片', icon: 'none' }); return } const orderIds = this.data.orders.filter((row) => row.status === '待自提').map((row) => row._id); const modal = await new Promise((resolve) => wx.showModal({ title: '整场无人放置', editable: true, placeholderText: '填写固定放置地点', success: resolve })); if (!modal.confirm || !modal.content.trim()) return; const res = await app.call('placeOrderAtLocation', { batchStationId: this.data.batchStationId, orderIds, locationNote: modal.content.trim(), images: this.data.proofImages }); wx.showToast({ title: res.ok ? '整场已放置' : (res.msg || '放置失败'), icon: 'none' }); if (res.ok) this.setData({ proofImages: [] }); this.loadPrep() },
  async finishNoShow() { if (!this.data.proofImages.length) { wx.showToast({ title: '请先上传收尾照片', icon: 'none' }); return } const orderIds = this.data.orders.filter((row) => row.status === '待自提').map((row) => row._id); const res = await app.call('finishNoShow', { batchStationId: this.data.batchStationId, orderIds, images: this.data.proofImages }); wx.showToast({ title: res.ok ? '未取订单已收尾' : (res.msg || '处理失败'), icon: 'none' }); if (res.ok) this.setData({ proofImages: [] }); this.loadPrep() },
  async endPickup() { let res = await app.call('endPickupSession', { batchStationId: this.data.batchStationId }); if (!res.ok && this.data.role === 'superAdmin' && /窗口结束前/.test(res.msg || '')) { const modal = await new Promise((resolve) => wx.showModal({ title: '异常提前结束', editable: true, placeholderText: '二次确认并填写原因', success: resolve })); if (modal.confirm && modal.content.trim()) res = await app.call('endPickupSession', { batchStationId: this.data.batchStationId, earlyEndConfirmed: true, reason: modal.content.trim() }) } wx.showToast({ title: res.ok ? '本场已完成' : (res.msg || '仍有订单未处理'), icon: 'none' }); if (res.ok) this.loadStations() }
})
